# Version catalog is a central place for you to declare and version dependencies
# https://docs.gradle.org/current/userguide/platforms.html#sub:version-catalog
# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
kotlin = "2.3.21"
ktor = "3.4.3"

kotlinxDatetime = "0.7.1"
kotlinxSerializationJSON = "1.9.0"
kotlinxCoroutines = "1.10.2"

logback = "1.5.32"
docker-java = "3.7.1"
jackson = "2.17.1"
kaml = "0.60.0"
sshd = "2.12.1"

[libraries]

# Kotlin
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinSerializationPlugin = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
# KotlinX
kotlinxDatetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinxSerialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJSON" }
kotlinxCoroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }

# Ktor Server
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktor-server-websockets = { module = "io.ktor:ktor-server-websockets", version.ref = "ktor" }

ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

ktor-server-rate-limit = { module = "io.ktor:ktor-server-rate-limit-jvm", version.ref = "ktor" }
ktor-server-status-pages = { module = "io.ktor:ktor-server-status-pages", version.ref = "ktor" }
ktor-server-double-receive = { module = "io.ktor:ktor-server-double-receive", version.ref = "ktor" }
ktor-server-cors = { module = "io.ktor:ktor-server-cors", version.ref = "ktor" }

# cbor
ktor-server-cbor = { module = "io.ktor:ktor-serialization-kotlinx-cbor", version.ref = "ktor" }

# Ktor Client
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }

# Logging
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

# Docker
docker-java = { module = "com.github.docker-java:docker-java", version.ref = "docker-java" }
docker-java-httpclient5 = { module = "com.github.docker-java:docker-java-transport-httpclient5", version.ref = "docker-java" }

# Jackson
jackson-yaml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml", version.ref = "jackson" }

# YAML
kaml = { module = "com.charleskorn.kaml:kaml", version.ref = "kaml" }

# SSHD
sshd-core = { module = "org.apache.sshd:sshd-core", version.ref = "sshd" }

# Libraries can be bundled together for easier import
[bundles]
kotlinxEcosystem = [
    "kotlinxDatetime",
    "kotlinxSerialization",
    "kotlinxCoroutines"
]

ktorServer = [
    "ktor-server-core",
    "ktor-server-netty",
    "ktor-server-websockets",
    "ktor-server-content-negotiation",
    "ktor-serialization-kotlinx-json",
    "ktor-server-rate-limit",
    "ktor-server-status-pages",
    "ktor-server-double-receive",
    "ktor-server-cors",
    "ktor-server-cbor"
]

ktorClient = [
    "ktor-client-core",
    "ktor-client-cio",
    "ktor-client-content-negotiation"
]

docker = [
    "docker-java",
    "docker-java-httpclient5"
]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinPluginSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }

shadow = { id = "com.gradleup.shadow", version = "9.0.0" }